# compose 파일 버전
version: "3.8"
services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      # Kafka 노드 ID 설정
      KAFKA_NODE_ID: 1
      # Kafka 리스너 보안 프로토콜 맵 설정
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      # Kafka 노출된 리스너 설정
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      # Kafka 프로세스 역할 설정
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # Kafka 컨트롤러 쿼럼 투표자 설정
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      # Kafka 리스너 설정
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      # Kafka 브로커 간 리스너 이름 설정
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      # Kafka 컨트롤러 리스너 이름 설정
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # Kafka 클러스터 ID 설정
      CLUSTER_ID: 'localhost:9092'
      # Kafka 오프셋 토픽 복제 팩터 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Kafka 그룹 초기 리밸런스 지연 설정
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # Kafka 트랜잭션 상태 로그 최소 ISR 설정
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Kafka 트랜잭션 상태 로그 복제 팩터 설정
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # Kafka 로그 디렉토리 설정
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./docker-log/kafka-data:/data/kafka

  # 서비스 명
  mongodb:
    # 사용할 이미지
    image: mongo:latest
    # 컨테이너명 설정
    container_name: mongodb
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "27017:27017"
    # 환경 변수 설정
    environment:
      # MongoDB 계정 및 패스워드 설정 옵션
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # 볼륨 설정
    volumes:
      - ./docker-log/mongo-data:/data/mongodb